name: softbol
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0  # Actualizado a la versión compatible con Cloud Firestore
  cloud_firestore: ^5.4.2  # Actualizado para ser compatible con firebase_core
  path_provider: ^2.0.1  # Para el manejo de rutas
  flutter_native_splash: ^2.0.5  # Para el splash screen
  cupertino_icons: ^1.0.8  # Iconos para iOS
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.0  # Para generar adaptadores

flutter:
  uses-material-design: true

  assets:
    - assets/images/GigantesLogo.png
    - assets/images/fondonegroo.png
    - assets/images/fondonegromarcosnaranja.jpg
    - assets/fonts/

  fonts:
    - family: GigantesFont
      fonts:
        - asset: assets/fonts/GigantesFont.ttf

flutter_native_splash:
  color: "#000000"
  image: assets/images/GigantesLogo.png
  android: true
  ios: true
  web: false
  android_gravity: center
